/* KPSS kart havuzu - tüm dersler tek dosyada.
   Yeni kart eklemek icin ilgili dersin blogunda yeni nesne olustur. */

const KARTLAR = [

  // --- İslamiyet Öncesi Türk Tarihi ---
  { id: 'TR001', ders: 'tarih', konu: 'İslamiyet Öncesi Türk Tarihi',
    on: 'Türklerin bilinen ilk devleti hangisidir?',
    arka: 'Asya Hun Devleti (Büyük Hun). En güçlü dönemi Mete Han zamanıdır.' },
  { id: 'TR002', ders: 'tarih', konu: 'İslamiyet Öncesi Türk Tarihi',
    on: '"Türk" adının geçtiği ilk yazılı Türk kaynağı nedir?',
    arka: 'Orhun (Göktürk) Kitabeleri. II. Göktürk Devleti döneminde dikilmiştir.' },
  { id: 'TR003', ders: 'tarih', konu: 'İslamiyet Öncesi Türk Tarihi',
    on: 'Orhun Kitabeleri kim tarafından, hangi yıl okundu?',
    arka: 'Danimarkalı bilgin Vilhelm Thomsen tarafından 1893 yılında okundu.' },
  { id: 'TR004', ders: 'tarih', konu: 'İslamiyet Öncesi Türk Tarihi',
    on: 'Yerleşik hayata geçen ilk Türk devleti hangisidir?',
    arka: 'Uygurlar. Mani dinini benimsemeleri göçebe yaşamdan uzaklaşmalarında etkili olmuştur.' },
  { id: 'TR005', ders: 'tarih', konu: 'İslamiyet Öncesi Türk Tarihi',
    on: 'Mete Han\'ın orduda getirdiği düzenleme nedir?',
    arka: 'Onluk sistem: ordunun 10, 100, 1.000 ve 10.000\'lik birliklere ayrılması.' },

  // --- Türk-İslam Tarihi ---
  { id: 'TR006', ders: 'tarih', konu: 'İlk Türk-İslam Devletleri',
    on: 'Talas Savaşı hangi yıl, kimler arasında yapıldı?',
    arka: '751 yılında Abbasi–Karluk ittifakı ile Çin arasında. Türklerin İslamiyet\'i kabul sürecini hızlandırmıştır.' },
  { id: 'TR007', ders: 'tarih', konu: 'İlk Türk-İslam Devletleri',
    on: 'İlk Türk-İslam devleti hangisidir?',
    arka: 'Karahanlılar. Resmî dili Türkçe olan ilk Türk-İslam devletidir.' },
  { id: 'TR008', ders: 'tarih', konu: 'İlk Türk-İslam Devletleri',
    on: 'Malazgirt Savaşı: yıl, taraflar, sonuç?',
    arka: '1071. Büyük Selçuklu (Sultan Alparslan) – Bizans (Romanos Diogenes). Anadolu\'nun kapıları Türklere açıldı.' },
  { id: 'TR009', ders: 'tarih', konu: 'İlk Türk-İslam Devletleri',
    on: 'Miryokefalon Savaşı\'nın önemi nedir?',
    arka: '1176. II. Kılıçarslan Bizans\'ı yendi. Anadolu\'nun kesin olarak Türk yurdu olduğu kabul edildi.' },

  // --- Osmanlı Kuruluş ve Yükselme ---
  { id: 'TR010', ders: 'tarih', konu: 'Osmanlı Kuruluş ve Yükselme',
    on: 'Osmanlıların Rumeli\'ye ilk geçişi nerede ve ne zaman oldu?',
    arka: 'Çimpe Kalesi, 1353. Orhan Bey döneminde, Süleyman Paşa komutasında.' },
  { id: 'TR011', ders: 'tarih', konu: 'Osmanlı Kuruluş ve Yükselme',
    on: 'Ankara Savaşı ve sonucu?',
    arka: '1402. Yıldırım Bayezid – Timur. Osmanlı yenildi, Fetret Devri (1402–1413) başladı.' },
  { id: 'TR012', ders: 'tarih', konu: 'Osmanlı Kuruluş ve Yükselme',
    on: 'İstanbul\'un fethi ve çağ değişimi?',
    arka: '1453, Fatih Sultan Mehmed. Orta Çağ kapandı, Yeni Çağ başladı.' },
  { id: 'TR013', ders: 'tarih', konu: 'Osmanlı Kuruluş ve Yükselme',
    on: 'Otlukbeli Savaşı kimler arasında yapıldı?',
    arka: '1473. Fatih Sultan Mehmed – Akkoyunlu hükümdarı Uzun Hasan.' },
  { id: 'TR014', ders: 'tarih', konu: 'Osmanlı Kuruluş ve Yükselme',
    on: 'Çaldıran Savaşı: yıl ve taraflar?',
    arka: '1514. Yavuz Sultan Selim – Safevi hükümdarı Şah İsmail. Doğu Anadolu Osmanlı\'ya katıldı.' },
  { id: 'TR015', ders: 'tarih', konu: 'Osmanlı Kuruluş ve Yükselme',
    on: 'Halifelik Osmanlı\'ya hangi seferle geçti?',
    arka: 'Mısır Seferi. Mercidabık (1516) ve Ridaniye (1517) savaşlarıyla Memlük Devleti yıkıldı.' },
  { id: 'TR016', ders: 'tarih', konu: 'Osmanlı Kuruluş ve Yükselme',
    on: 'Mohaç Meydan Muharebesi ve sonucu?',
    arka: '1526, Kanuni Sultan Süleyman. Macaristan\'ın büyük bölümü Osmanlı egemenliğine girdi.' },
  { id: 'TR017', ders: 'tarih', konu: 'Osmanlı Kuruluş ve Yükselme',
    on: 'Preveze Deniz Savaşı\'nın önemi?',
    arka: '1538. Barbaros Hayreddin Paşa Haçlı donanmasını yendi; Akdeniz\'de Osmanlı üstünlüğü kesinleşti.' },

  // --- Duraklama, Gerileme, Dağılma ---
  { id: 'TR018', ders: 'tarih', konu: 'Duraklama, Gerileme, Dağılma',
    on: 'Karlofça Antlaşması\'nın önemi nedir?',
    arka: '1699. Osmanlı\'nın ilk büyük toprak kaybıdır; Gerileme Dönemi\'nin başlangıcı sayılır.' },
  { id: 'TR019', ders: 'tarih', konu: 'Duraklama, Gerileme, Dağılma',
    on: 'Lale Devri hangi antlaşmayla başlar, hangi olayla biter?',
    arka: 'Pasarofça Antlaşması (1718) ile başlar, Patrona Halil İsyanı (1730) ile biter.' },
  { id: 'TR020', ders: 'tarih', konu: 'Duraklama, Gerileme, Dağılma',
    on: 'Küçük Kaynarca Antlaşması neden önemlidir?',
    arka: '1774, Rusya ile. Kırım\'a bağımsızlık verildi; Rusya Osmanlı\'daki Ortodokslar üzerinde söz hakkı elde etti.' },
  { id: 'TR021', ders: 'tarih', konu: 'Duraklama, Gerileme, Dağılma',
    on: 'Nizam-ı Cedid ordusunu kim kurdu?',
    arka: 'III. Selim. Yeniçeri Ocağı dışında kurulan yeni düzenli ordudur.' },
  { id: 'TR022', ders: 'tarih', konu: 'Duraklama, Gerileme, Dağılma',
    on: 'Sened-i İttifak neden önemlidir?',
    arka: '1808, II. Mahmud dönemi. Padişahın otoritesinin ilk kez sınırlandırıldığı belgedir.' },
  { id: 'TR023', ders: 'tarih', konu: 'Duraklama, Gerileme, Dağılma',
    on: 'Tanzimat Fermanı hangi yıl, hangi padişah döneminde ilan edildi?',
    arka: '1839, Sultan Abdülmecid. Kanun üstünlüğü fikrinin ilk kez benimsendiği belgedir.' },
  { id: 'TR024', ders: 'tarih', konu: 'Duraklama, Gerileme, Dağılma',
    on: 'I. Meşrutiyet ve Kanun-i Esasi?',
    arka: '1876, II. Abdülhamid döneminde ilan edildi. Osmanlı\'nın ilk anayasasıdır; halk ilk kez yönetime katıldı.' },

  // --- XX. Yüzyıl ve Kurtuluş Savaşı ---
  { id: 'TR025', ders: 'tarih', konu: 'XX. Yüzyıl Başı Osmanlı',
    on: 'Trablusgarp Savaşı kiminle yapıldı, hangi antlaşmayla bitti?',
    arka: '1911–1912, İtalya ile. Uşi Antlaşması ile sona erdi; Osmanlı Kuzey Afrika\'daki son toprağını kaybetti.' },
  { id: 'TR026', ders: 'tarih', konu: 'XX. Yüzyıl Başı Osmanlı',
    on: 'Edirne II. Balkan Savaşı\'nda mı geri alındı?',
    arka: 'Evet. I. Balkan Savaşı\'nda kaybedilen Edirne ve Kırklareli, II. Balkan Savaşı sırasında geri alındı.' },
  { id: 'TR027', ders: 'tarih', konu: 'XX. Yüzyıl Başı Osmanlı',
    on: 'Mondros Ateşkes Antlaşması ne zaman imzalandı?',
    arka: '30 Ekim 1918. 7. maddesiyle İtilaf Devletleri\'ne işgal hakkı tanınmıştır.' },
  { id: 'TR028', ders: 'tarih', konu: 'Kurtuluş Savaşı Hazırlık',
    on: 'Amasya Genelgesi neden önemlidir?',
    arka: '22 Haziran 1919. Kurtuluş Savaşı\'nın gerekçesi, amacı ve yöntemi ilk kez birlikte açıklanmıştır.' },
  { id: 'TR029', ders: 'tarih', konu: 'Kurtuluş Savaşı Hazırlık',
    on: 'Erzurum Kongresi\'nin ayırt edici özelliği nedir?',
    arka: '23 Temmuz 1919. Toplanış biçimi bölgesel, alınan kararlar ulusaldır.' },
  { id: 'TR030', ders: 'tarih', konu: 'Kurtuluş Savaşı Hazırlık',
    on: 'Misak-ı Millî hangi mecliste kabul edildi?',
    arka: '28 Ocak 1920\'de son Osmanlı Mebusan Meclisi tarafından kabul edildi.' },
  { id: 'TR031', ders: 'tarih', konu: 'Kurtuluş Savaşı Muharebeleri',
    on: 'Sakarya Meydan Muharebesi\'nin sonucu nedir?',
    arka: '23 Ağustos – 13 Eylül 1921. 1683 Viyana bozgunundan beri süren geri çekilme sona erdi; savunmadan taarruza geçildi.' },
  { id: 'TR032', ders: 'tarih', konu: 'Kurtuluş Savaşı Muharebeleri',
    on: 'Büyük Taarruz ne zaman başladı, hangi muharebeyle sonuçlandı?',
    arka: '26 Ağustos 1922\'de başladı, 30 Ağustos 1922 Başkomutanlık Meydan Muharebesi ile zaferle sonuçlandı.' },
  { id: 'TR033', ders: 'tarih', konu: 'Kurtuluş Savaşı Muharebeleri',
    on: 'Mudanya ve Lozan tarihleri?',
    arka: 'Mudanya Ateşkes Antlaşması: 11 Ekim 1922. Lozan Barış Antlaşması: 24 Temmuz 1923.' },

  // --- İnkılaplar ve Atatürk Dönemi ---
  { id: 'TR034', ders: 'tarih', konu: 'Atatürk İlke ve İnkılapları',
    on: 'Saltanat ve halifelik hangi tarihlerde kaldırıldı?',
    arka: 'Saltanat: 1 Kasım 1922. Halifelik: 3 Mart 1924.' },
  { id: 'TR035', ders: 'tarih', konu: 'Atatürk İlke ve İnkılapları',
    on: 'Cumhuriyet ne zaman ilan edildi?',
    arka: '29 Ekim 1923. Aynı gün Mustafa Kemal ilk cumhurbaşkanı seçildi.' },
  { id: 'TR036', ders: 'tarih', konu: 'Atatürk Dönemi Dış Politika',
    on: 'Montrö Boğazlar Sözleşmesi hangi yıl imzalandı?',
    arka: '1936. Boğazlar üzerindeki Türk egemenliği tam olarak sağlandı.' },
  { id: 'TR037', ders: 'tarih', konu: 'Atatürk Dönemi Dış Politika',
    on: 'Hatay ne zaman anavatana katıldı?',
    arka: '1939. Atatürk\'ün ölümünden sonra tamamlanan son toprak kazanımıdır.' },

  // --- Fiziki Coğrafya ---
  { id: 'CG001', ders: 'cografya', konu: 'Coğrafi Konum',
    on: 'Türkiye\'nin matematik konumu nedir?',
    arka: '36°–42° kuzey enlemleri, 26°–45° doğu boylamları arasında.' },
  { id: 'CG002', ders: 'cografya', konu: 'Coğrafi Konum',
    on: 'Türkiye\'nin doğusu ile batısı arasında kaç saat fark vardır?',
    arka: '19 boylam farkı vardır, bu da yaklaşık 76 dakika (1 saat 16 dk) yerel saat farkı demektir.' },
  { id: 'CG003', ders: 'cografya', konu: 'Yer Şekilleri',
    on: 'Türkiye\'nin en yüksek dağı ve yüksekliği?',
    arka: 'Ağrı Dağı, 5.137 metre. Volkanik kökenlidir.' },
  { id: 'CG004', ders: 'cografya', konu: 'Yer Şekilleri',
    on: 'Ege\'de dağların denize dik uzanmasının sonuçları nelerdir?',
    arka: 'Deniz etkisi iç kesimlere sokulur, kıyı girinti-çıkıntısı artar, ulaşım kolaylaşır, limanlar art bölgeyle bağlantılıdır.' },
  { id: 'CG005', ders: 'cografya', konu: 'İklim ve Bitki Örtüsü',
    on: 'Akdeniz ikliminin doğal bitki örtüsü nedir?',
    arka: 'Maki: kuraklığa dayanıklı, bodur, çoğu her dem yeşil çalı topluluğu.' },
  { id: 'CG006', ders: 'cografya', konu: 'İklim ve Bitki Örtüsü',
    on: 'İç Anadolu\'nun doğal bitki örtüsü nedir?',
    arka: 'Bozkır (step): ilkbahar yağışlarıyla yeşeren, yazın kuruyan otsu bitkiler.' },
  { id: 'CG007', ders: 'cografya', konu: 'İklim ve Bitki Örtüsü',
    on: 'Karadeniz iklimini ayıran temel özellik nedir?',
    arka: 'Her mevsim yağışlı olmasıdır. Bu nedenle doğal bitki örtüsü gür ormandır.' },
  { id: 'CG008', ders: 'cografya', konu: 'Hidrografya',
    on: 'Türkiye topraklarından doğup denize dökülen en uzun akarsu?',
    arka: 'Kızılırmak, yaklaşık 1.355 km. Karadeniz\'e dökülür.' },
  { id: 'CG009', ders: 'cografya', konu: 'Hidrografya',
    on: 'Türkiye\'nin en büyük gölü ve oluşumu?',
    arka: 'Van Gölü. Nemrut Dağı\'ndan çıkan lavların vadiyi kapatmasıyla oluşmuş volkanik set gölüdür.' },
  { id: 'CG010', ders: 'cografya', konu: 'Hidrografya',
    on: 'Türkiye\'nin en büyük baraj gölü hangisidir?',
    arka: 'Atatürk Barajı Gölü. Fırat Nehri üzerinde, GAP kapsamındadır.' },

  // --- Beşeri ve Ekonomik Coğrafya ---
  { id: 'CG011', ders: 'cografya', konu: 'Nüfus ve Yerleşme',
    on: 'Türkiye\'de nüfus yoğunluğunun en fazla olduğu il?',
    arka: 'İstanbul. Sanayi, ticaret ve hizmet sektörünün yoğunluğu nedeniyle en çok göç alan ildir.' },
  { id: 'CG012', ders: 'cografya', konu: 'Nüfus ve Yerleşme',
    on: 'Türkiye\'de nüfusun seyrek olduğu alanların ortak özellikleri?',
    arka: 'Yüksek ve engebeli araziler, karasal iklimin sert olduğu bölgeler, sanayi ve tarım olanaklarının kısıtlı olduğu yerler.' },
  { id: 'CG013', ders: 'cografya', konu: 'Tarım ve Hayvancılık',
    on: 'Türkiye hangi tarım ürününde dünya birincisidir?',
    arka: 'Fındık. Üretim Doğu Karadeniz kıyılarında (özellikle Ordu, Giresun) yoğunlaşır.' },
  { id: 'CG014', ders: 'cografya', konu: 'Tarım ve Hayvancılık',
    on: 'Çay tarımı hangi koşulları gerektirir ve nerede yapılır?',
    arka: 'Her mevsim yağış, ılıman sıcaklık ve asitli toprak gerektirir. Doğu Karadeniz kıyı kuşağında (Rize çevresi) yetiştirilir.' },
  { id: 'CG015', ders: 'cografya', konu: 'Madenler ve Enerji',
    on: 'Türkiye hangi madende dünya rezervinde ilk sıradadır?',
    arka: 'Bor. Rezervlerin büyük bölümü Balıkesir, Kütahya, Eskişehir ve Bursa çevresindedir.' },
  { id: 'CG016', ders: 'cografya', konu: 'Madenler ve Enerji',
    on: 'Taş kömürü hangi havzada çıkarılır?',
    arka: 'Zonguldak havzası. Türkiye\'nin tek taş kömürü üretim alanıdır.' },
  { id: 'CG017', ders: 'cografya', konu: 'Coğrafi Bölgeler',
    on: 'GAP kaç ili kapsar ve hangi nehirler üzerindedir?',
    arka: '9 ili kapsar. Fırat ve Dicle nehirleri üzerinde kurulmuştur.' },
  { id: 'CG018', ders: 'cografya', konu: 'Coğrafi Bölgeler',
    on: 'Yüz ölçümü en büyük ve en küçük coğrafi bölgelerimiz?',
    arka: 'En büyük: Doğu Anadolu Bölgesi. En küçük: Güneydoğu Anadolu Bölgesi.' },
  { id: 'CG019', ders: 'cografya', konu: 'Yer Şekilleri',
    on: 'Kuzey Anadolu Fay Hattı hangi yönde uzanır?',
    arka: 'Doğu–batı doğrultusunda uzanır. Türkiye\'nin en aktif deprem kuşağıdır.' },
  { id: 'CG020', ders: 'cografya', konu: 'Tarım ve Hayvancılık',
    on: 'Türkiye\'nin en büyük ovası hangisidir?',
    arka: 'Konya Ovası. İç Anadolu\'da yer alır, tahıl tarımında öne çıkar.' },

  { id: 'VT001', ders: 'vatandaslik', konu: 'Anayasa Genel Esaslar',
    on: '1982 Anayasası ne zaman kabul edildi?',
    arka: '7 Kasım 1982 tarihinde halk oylamasıyla kabul edildi ve aynı gün yürürlüğe girdi.' },
  { id: 'VT002', ders: 'vatandaslik', konu: 'Anayasa Genel Esaslar',
    on: 'Anayasanın değiştirilemez ilk üç maddesi neyi düzenler?',
    arka: '1. madde devletin şeklini (Cumhuriyet), 2. madde Cumhuriyetin niteliklerini, 3. madde devletin bütünlüğü, resmî dili, bayrağı, millî marşı ve başkentini düzenler.' },
  { id: 'VT003', ders: 'vatandaslik', konu: 'Anayasa Genel Esaslar',
    on: 'Türkiye Cumhuriyeti\'nin nitelikleri nelerdir?',
    arka: 'Demokratik, laik, sosyal bir hukuk devleti; Atatürk milliyetçiliğine bağlı, insan haklarına saygılı (md. 2).' },

  { id: 'VT004', ders: 'vatandaslik', konu: 'Yasama',
    on: 'TBMM kaç milletvekilinden oluşur?',
    arka: '600 milletvekilinden oluşur.' },
  { id: 'VT005', ders: 'vatandaslik', konu: 'Yasama',
    on: 'Milletvekili seçilme yaşı kaçtır?',
    arka: 'On sekiz yaşını dolduran her Türk vatandaşı milletvekili seçilebilir.' },
  { id: 'VT006', ders: 'vatandaslik', konu: 'Yasama',
    on: 'TBMM seçimleri kaç yılda bir yapılır?',
    arka: 'Beş yılda bir. Cumhurbaşkanı seçimiyle aynı günde yapılır.' },
  { id: 'VT007', ders: 'vatandaslik', konu: 'Yasama',
    on: 'Kanun teklif etme yetkisi kime aittir?',
    arka: 'Milletvekillerine aittir. 2017 değişikliğiyle "kanun tasarısı" (Bakanlar Kurulu teklifi) kaldırılmıştır.' },
  { id: 'VT008', ders: 'vatandaslik', konu: 'Yasama',
    on: 'TBMM\'nin toplantı ve karar yeter sayısı nedir?',
    arka: 'Toplantı yeter sayısı üye tamsayısının en az üçte biri (200); karar yeter sayısı toplantıya katılanların salt çoğunluğudur (en az 151).' },

  { id: 'VT009', ders: 'vatandaslik', konu: 'Yürütme',
    on: 'Cumhurbaşkanı seçilme şartları nelerdir?',
    arka: 'Kırk yaşını doldurmuş, yükseköğrenim yapmış, milletvekili seçilme yeterliliğine sahip Türk vatandaşı olmak.' },
  { id: 'VT010', ders: 'vatandaslik', konu: 'Yürütme',
    on: 'Cumhurbaşkanının görev süresi ve dönem sınırı nedir?',
    arka: 'Görev süresi beş yıldır. Bir kişi en fazla iki dönem seçilebilir.' },
  { id: 'VT011', ders: 'vatandaslik', konu: 'Yürütme',
    on: 'Cumhurbaşkanlığı kararnamesi hangi konularda çıkarılamaz?',
    arka: 'Temel haklar, kişi hakları ve ödevleri ile siyasi haklar ve ödevler kararnameyle düzenlenemez. Kanunda açıkça düzenlenen konularda da çıkarılamaz.' },
  { id: 'VT012', ders: 'vatandaslik', konu: 'Yürütme',
    on: 'Olağanüstü hâl kim tarafından, ne kadar süreyle ilan edilir?',
    arka: 'Cumhurbaşkanı tarafından, yurdun tamamında veya bir bölgesinde en fazla altı ay süreyle ilan edilir. TBMM onayına sunulur.' },

  { id: 'VT013', ders: 'vatandaslik', konu: 'Yargı',
    on: 'Anayasa Mahkemesi kaç üyeden oluşur?',
    arka: '15 üyeden oluşur. Üyeler 12 yıl için seçilir ve bir kişi iki kez seçilemez.' },
  { id: 'VT014', ders: 'vatandaslik', konu: 'Yargı',
    on: 'Hâkimler ve Savcılar Kurulu kaç üyelidir?',
    arka: '13 üyeden oluşur, iki daire hâlinde çalışır. Başkanı Adalet Bakanı\'dır.' },
  { id: 'VT015', ders: 'vatandaslik', konu: 'Yargı',
    on: 'Sayıştay\'ın görevi nedir?',
    arka: 'TBMM adına, kamu idarelerinin gelir, gider ve mallarını denetler; sorumluların hesap ve işlemlerini kesin hükme bağlar.' },
  { id: 'VT016', ders: 'vatandaslik', konu: 'Yargı',
    on: 'Bireysel başvuru hakkı nedir?',
    arka: 'Anayasada güvence altına alınmış temel hak ve özgürlüğü kamu gücü tarafından ihlal edilen kişinin, olağan kanun yollarını tükettikten sonra Anayasa Mahkemesi\'ne başvurmasıdır.' },

  { id: 'VT017', ders: 'vatandaslik', konu: 'Temel Hak ve Hürriyetler',
    on: 'Temel hak ve hürriyetler nasıl sınırlandırılabilir?',
    arka: 'Yalnızca kanunla, Anayasanın ilgili maddelerinde belirtilen sebeplere bağlı olarak, özlerine dokunulmaksızın ve ölçülülük ilkesine uygun biçimde.' },
  { id: 'VT018', ders: 'vatandaslik', konu: 'Anayasa Değişikliği',
    on: 'Anayasa değişikliği teklifi için kaç milletvekili gerekir?',
    arka: 'TBMM üye tamsayısının en az üçte biri, yani 200 milletvekili.' },
  { id: 'VT019', ders: 'vatandaslik', konu: 'Anayasa Değişikliği',
    on: 'Anayasa değişikliğinde 3/5 ve 2/3 çoğunluğun sonucu nedir?',
    arka: '360–399 oy (3/5): halk oylamasına sunulur. 400 ve üzeri (2/3): Cumhurbaşkanı isterse doğrudan yayımlar, isterse halk oylamasına sunar.' },
  { id: 'VT020', ders: 'vatandaslik', konu: 'Temel Hukuk',
    on: 'Hukuk kurallarının yaptırım türleri nelerdir?',
    arka: 'Ceza, cebrî icra, tazminat, hükümsüzlük (butlan) ve iptal.' },

  // --- Yazım Kuralları ---
  { id: 'TK001', ders: 'turkce', konu: 'Yazım Kuralları',
    on: '"de / da" ne zaman ayrı, ne zaman bitişik yazılır?',
    arka: 'Bulunma hâl eki ise BİTİŞİK: "Evde kimse yok." Bağlaç ise AYRI: "Ben de geldim." Ayırt etme yolu: cümleden çıkarıldığında anlam bozulmuyorsa bağlaçtır, ayrı yazılır.' },
  { id: 'TK002', ders: 'turkce', konu: 'Yazım Kuralları',
    on: '"ki" ne zaman ayrı yazılır?',
    arka: 'Bağlaç olan "ki" ayrı yazılır: "Duydum ki gelmişsin." İlgi zamiri ve sıfat yapan "-ki" bitişiktir: "seninki", "yarınki".' },
  { id: 'TK003', ders: 'turkce', konu: 'Yazım Kuralları',
    on: '"ki" bağlacının bitişik yazıldığı kalıplaşmış sözcükler hangileridir?',
    arka: 'Oysaki, mademki, halbuki, sanki, çünkü, belki, meğerki, illaki. Bunlar kural dışıdır, ezberlenmelidir.' },
  { id: 'TK004', ders: 'turkce', konu: 'Yazım Kuralları',
    on: 'Soru eki "mi" nasıl yazılır?',
    arka: 'Her zaman AYRI yazılır: "Geldi mi?" Ancak kendisinden sonra gelen ekler ona bitişik yazılır: "Gelecek misin?", "Güzel mi güzel."' },
  { id: 'TK005', ders: 'turkce', konu: 'Yazım Kuralları',
    on: 'Özel adlara gelen ekler nasıl yazılır?',
    arka: 'Kesme işaretiyle ayrılır: "Ankara\'da", "Ahmet\'in". Ancak kurum, kuruluş ve kuruluş bildiren adlarda kesme kullanılmaz: "Türk Dil Kurumundan".' },
  { id: 'TK006', ders: 'turkce', konu: 'Yazım Kuralları',
    on: 'Özel ada getirilen yapım eki ve sonrasındaki ekler nasıl yazılır?',
    arka: 'Kesmeyle ayrılmaz: "Türkçenin", "Avrupalılaşmak", "Konyalı". Yapım eki geldiği anda kesme kalkar.' },
  { id: 'TK007', ders: 'turkce', konu: 'Yazım Kuralları',
    on: 'Sayılar metin içinde nasıl yazılır?',
    arka: 'Metin içinde yazıyla yazılır ve her sözcük ayrı yazılır: "üç yüz altmış beş". Ancak para, ölçü, istatistik ve resmî belgelerde rakam kullanılır.' },
  { id: 'TK008', ders: 'turkce', konu: 'Yazım Kuralları',
    on: '"ile" sözcüğü ne zaman bitişik yazılır ve nasıl değişir?',
    arka: 'Ünsüzle biten sözcüğe bitişince "-le/-la": "arabayla". Ünlüyle bitene "-yle/-yla": "annesiyle". Büyük ünlü uyumuna uyar.' },

  // --- Noktalama ---
  { id: 'TK009', ders: 'turkce', konu: 'Noktalama',
    on: 'Noktalı virgül hangi durumlarda kullanılır?',
    arka: 'Virgülle ayrılmış öğeleri gruplandırırken ve anlamca bağlı bağımsız cümleleri ayırırken: "Erkek çocuklara Ali, Veli; kız çocuklara Ayşe, Fatma adları verilir."' },
  { id: 'TK010', ders: 'turkce', konu: 'Noktalama',
    on: 'İki nokta hangi durumlarda kullanılır?',
    arka: 'Kendisinden sonra açıklama, örnek veya alıntı geldiğinde: "Şunları aldım: defter, kalem, silgi." Ayrıca karşılıklı konuşmalarda konuşan kişinin adından sonra.' },
  { id: 'TK011', ders: 'turkce', konu: 'Noktalama',
    on: 'Kesme işareti hangi durumlarda KULLANILMAZ?',
    arka: 'Kurum ve kuruluş adlarında, akım/çağ/dönem adlarında, özel ada getirilen yapım ekinden sonra, kısaltmalara gelen eklerde değil (onlarda kullanılır) - dikkat: "TDK\'den" doğru, "Millî Eğitim Bakanlığına" doğrudur.' },
  { id: 'TK012', ders: 'turkce', konu: 'Noktalama',
    on: 'Virgül özneden sonra ne zaman konur?',
    arka: 'Özne karışıklığa yol açabilecekse konur: "Genç, adama seslendi." Burada virgül "genç" sözcüğünü özne yapar; virgülsüz hâlde sıfat olur.' },

  // --- Anlatım Bozuklukları ---
  { id: 'TK013', ders: 'turkce', konu: 'Anlatım Bozukluğu',
    on: 'Anlama dayalı anlatım bozukluğu türleri nelerdir?',
    arka: 'Gereksiz sözcük kullanımı, sözcüğün yanlış anlamda kullanılması, anlam belirsizliği, mantık hatası, deyim yanlışı, sözcüğün yanlış yerde kullanılması.' },
  { id: 'TK014', ders: 'turkce', konu: 'Anlatım Bozukluğu',
    on: 'Yapıya dayalı anlatım bozukluğu türleri nelerdir?',
    arka: 'Öğe eksikliği (özne, nesne, tümleç), tamlama yanlışı, özne-yüklem uyumsuzluğu, çatı uyuşmazlığı, ek yanlışlığı, tamlayan eksikliği.' },
  { id: 'TK015', ders: 'turkce', konu: 'Anlatım Bozukluğu',
    on: 'Nesne eksikliğine örnek ver ve düzelt.',
    arka: '"Kitabı aldı ve masaya koydu." doğru. Ancak "Kitabı okudu ve rafa yerleştirdi." gibi ortak nesne farklı hâl istiyorsa bozukluk olur. Örnek: "Bahçeyi suladı, çiçekleri topladı." - ortak nesne yoksa sorun yoktur; sorun ortak öğenin farklı ek istemesindedir.' },
  { id: 'TK016', ders: 'turkce', konu: 'Anlatım Bozukluğu',
    on: 'Çatı uyuşmazlığı nedir?',
    arka: 'Bağlı cümlelerin yüklemlerinden biri etken, diğeri edilgen olduğunda ortaya çıkar: "Konu tartışıldı ve karara bağladılar." Doğrusu: "Konu tartışıldı ve karara bağlandı."' },
  { id: 'TK017', ders: 'turkce', konu: 'Anlatım Bozukluğu',
    on: 'Özne-yüklem uyumsuzluğu hangi durumlarda incelenir?',
    arka: 'Tekillik-çoğulluk uyumu ve kişi uyumu açısından. İnsan dışı çoğul özneler yüklemi tekil ister: "Kuşlar uçtu." Farklı kişiler varsa yüklem 1. veya 2. kişiye göre çekimlenir.' },
  { id: 'TK018', ders: 'turkce', konu: 'Anlatım Bozukluğu',
    on: 'Tamlayan eksikliğine örnek ver.',
    arka: '"Öğrencilerin başarısı ve geleceği önemlidir." doğru. "Sınıfın ve öğretmenin sorunları" gibi ortak tamlanan farklı tamlayan eki istiyorsa bozukluk olur: "Ali ile onun kardeşinin sorunları" biçiminde tamamlanmalıdır.' },
  { id: 'TK019', ders: 'turkce', konu: 'Anlatım Bozukluğu',
    on: 'Gereksiz sözcük kullanımı nasıl anlaşılır?',
    arka: 'Sözcük cümleden çıkarıldığında anlam değişmiyorsa gereksizdir: "Yukarı yukarı çıktık", "karşılıklı diyalog", "geri iade etmek", "ayrıca ilaveten".' },
  { id: 'TK020', ders: 'turkce', konu: 'Anlatım Bozukluğu',
    on: 'Anlam belirsizliği (iki anlamlılık) nasıl giderilir?',
    arka: 'Virgül kullanılarak veya sözcük sırası değiştirilerek: "Genç adama baktı" belirsizdir. "Genç, adama baktı" ya da "Adama genç baktı" biçiminde netleştirilir.' }
];
